title: "Belmont Chinese American Association"
organization: "Belmont Chinese American Association"
email: contact@bcaa-ma.org
timezone: UTC
baseurl: "/bcaa-ma"
permalink: "/:title/"
# permalink: "/:year/:month/:day/:title/"
logo: 'assets/images/bcaa-logo.png'
favicon: 'assets/images/favicon.ico'
author: dotobe
paginate: 30
paginate_path: "/news/page:num/"
disqus: 'bcaa-ma'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1
excerpt_separator: <!--more-->

# Authors
authors:
  sal:
    name: bcaa
    display_name: bcaa
    #avatar: 'assets/images/bcaa.png'
    #email: 
    #web: 
    #twitter:
    #description: ""

# Social
social:
  facebook: https://www.facebook.com/BCAAma

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives


defaults:
  # all files
  - scope:
      path: ""
    values:
      image: /assets/images/social-preview.png
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      read_time: true
      comments: false
      share: true
      related: true


# jekyll-archives:
#   enabled:
#     - year
#     - month
#     - tags
#   layout: archive
#   permalinks:
#     year: '/:year/'
#     month: '/:year/:month/'
#     day: '/:year/:month/:day/'
#     tag: '/tag/:name/'
#     category: '/category/:name/'
